services:
  - type: web
    name: book-summary-quiz-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
